# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rtruncnorm_cpp
#'
#' @description To sample from a multivariate truncated normal
#'
#' @param a Lower bounds vector
#' @param b Upper bounds vector
#' @param mean Vector of means
#' @param var Covariance matrix
NULL

#' @title rtmvnorm_cpp
#'
#' @description To sample from a multivariate truncated normal
#'
#' @param a Lower bounds vector
#' @param b Upper bounds vector
#' @param mean Vector of means
#' @param var Covariance matrix
NULL

#' @title dtruncnorm_cpp
#'
#' @description To get the density of a truncated normal
#'
#' @param a Lower bound vector
#' @param b Upper bound vector
#' @param mean Normal expectation vector
#' @param var Normal variance matrix
#' @param x Point to evaluate the density
NULL

#' @title dtmvnorm_cpp
#'
#' @description To get the density of a multivariate truncated normal
#'
#' @param a Lower bound vector
#' @param b Upper bound vector
#' @param mean Normal expectation vector
#' @param var Normal variance matrix
#' @param x Point to evaluate the density
NULL

#' @title max_range_cpp
#'
#' @description Max range to sample rho using rcpp
#'
#' @param Ws Spatial adjacency matrix
#' @param Wt Temporal adjacency matrix
#' @param rho_s Spatial parameter
#' @param rho_t Temporal parameter
#' @param rho_st Spatio-temporal parameter
#'
max_range_cpp <- function(Ws, Wt, rho_s, rho_t, rho_st) {
    .Call('_TGMRF_max_range_cpp', PACKAGE = 'TGMRF', Ws, Wt, rho_s, rho_t, rho_st)
}

#' @title cov
#'
#' @description Covariance matrix
#'
#' @param A Matrix to calculate covariances
#' @param B Matrix to restore covariance
#'
cov_cpp <- function(A, B) {
    invisible(.Call('_TGMRF_cov_cpp', PACKAGE = 'TGMRF', A, B))
}

#' @title buildQC_cpp
#'
#' @description CAR covariance matrix
#'
#' @param M A vector containing the number of neighbors
#' @param W A matrix containing the neighborhood structure
#' @param rho The spatial dependence parameter
#'
buildQC_cpp <- function(M, W, rho) {
    .Call('_TGMRF_buildQC_cpp', PACKAGE = 'TGMRF', M, W, rho)
}

#' @title buildQL_cpp
#'
#' @description Leroux covariance matrix
#'
#' @param R TO DO
#' @param rho Dependence parameter
#'
buildQL_cpp <- function(R, rho) {
    .Call('_TGMRF_buildQL_cpp', PACKAGE = 'TGMRF', R, rho)
}

#' @title buildQST_cpp
#'
#' @description Build a Spatio-temporal covariance matrix
#'
#' @param Ws Spatial neighborhod matrix
#' @param Wt Temporal neighborhod matrix
#' @param D A vector containing the number of neighbors on diagonal
#' @param rho_s Spatial dependence parameter
#' @param rho_t Temporal dependence parameter
#' @param rho_st Spatio-temporal dependence parameter
#'
buildQST_cpp <- function(Q, Ws, Wt, rho_s, rho_t, rho_st) {
    invisible(.Call('_TGMRF_buildQST_cpp', PACKAGE = 'TGMRF', Q, Ws, Wt, rho_s, rho_t, rho_st))
}

#' @title rmvnorm_cpp
#'
#' @description Random values from a multivariate normal
#'
#' @param n number of samples
#' @param mean vector of means
#' @param sigma covariance matrix
#'
rmvnorm_cpp <- function(sigma) {
    .Call('_TGMRF_rmvnorm_cpp', PACKAGE = 'TGMRF', sigma)
}

rtruncnorm_cpp <- function(a, b, mean, var) {
    .Call('_TGMRF_rtruncnorm_cpp', PACKAGE = 'TGMRF', a, b, mean, var)
}

rtmvnorm_cpp <- function(a, b, mean, var) {
    .Call('_TGMRF_rtmvnorm_cpp', PACKAGE = 'TGMRF', a, b, mean, var)
}

#' @title dtruncnorm
#'
#' @description To restore a point density of a truncated normal
#'
#' @param a Lower bound
#' @param b Upper bound
#' @param mean Normal expectation
#' @param var Normal variance
#' @param x Point to evaluate the density
#'
dtruncnorm <- function(x, a, b, mean, var) {
    .Call('_TGMRF_dtruncnorm', PACKAGE = 'TGMRF', x, a, b, mean, var)
}

dtruncnorm_cpp <- function(x, a, b, mean, var) {
    .Call('_TGMRF_dtruncnorm_cpp', PACKAGE = 'TGMRF', x, a, b, mean, var)
}

dtmvnorm_cpp <- function(x, a, b, mean, var) {
    .Call('_TGMRF_dtmvnorm_cpp', PACKAGE = 'TGMRF', x, a, b, mean, var)
}

#' @title dens_eps_pois_cpp
#'
#' @description To usage in MCMC estimation
#'
#' @param x Point to restore the density
#' @param params A list with some informations about the MCMC model.
#'
dens_eps_pois_cpp <- function(x, params, ele, eps, nu, Q, dsigma, Xbeta) {
    .Call('_TGMRF_dens_eps_pois_cpp', PACKAGE = 'TGMRF', x, params, ele, eps, nu, Q, dsigma, Xbeta)
}

#' @title dens_cpp
#'
#' @description To usage in MCMC estimation
#'
dens_cpp <- function(x_beta, x_eps, x_rho, x_nu, params, mu, cor_mat) {
    .Call('_TGMRF_dens_cpp', PACKAGE = 'TGMRF', x_beta, x_eps, x_rho, x_nu, params, mu, cor_mat)
}

#' @title POIMCAR
#'
#' @description Multivariate Poisson regression with CAR covariance structure
#'
#' @param nsim MCMC size
#' @param X Covariate matrix
#' @param y Response
#' @param E Offset
#' @param M Number of neighbors in each area
#' @param W Matrix with the neighborhood structure
#' @param N Dimension of the observations
#' @param P Dimension of the covariates
#' @param mean_beta Mean a priori to beta vector
#' @param tau_beta Variance a priori to beta vector
#' @param eta_nu Shape a priori to nu
#' @param psi_nu Rate a priori to nu
#' @param rangeRho Range to sample rho by using ARMS
#' @param type TGMRF type (1 to 6)
#' @param method ARMS (0) or Metropolis (1)
#' @param ninit Number of initial points in ARMS
#' @param maxpoint Maximum number of evaluation in each ARMS iteration
#' @param var_beta_met Variance of beta proposal
#' @param var_eps_met Variance of eps proposal
#' @param var_log_nu_met Variance of nu proposal
#' @param var_rho_met Variance of rho proposal
#' @param tau Vector of tau parameters to construct Q
#'
poimcar_cpp <- function(nsim, burnin, thin, eps, mu, beta, nu, rho_s, rho_t, rho_st, X, y, E, Ws, Wt, N, P, mean_beta, tau_beta, eta_nu, psi_nu, fix_rho_s, fix_rho_t, fix_rho_st, range_rho_s, range_rho_t, range_rho_st, type, var_beta_met, var_eps_met, var_rho_met, var_log_nu_met, verbose, c_beta, c_eps, c_nu, c_rho) {
    .Call('_TGMRF_poimcar_cpp', PACKAGE = 'TGMRF', nsim, burnin, thin, eps, mu, beta, nu, rho_s, rho_t, rho_st, X, y, E, Ws, Wt, N, P, mean_beta, tau_beta, eta_nu, psi_nu, fix_rho_s, fix_rho_t, fix_rho_st, range_rho_s, range_rho_t, range_rho_st, type, var_beta_met, var_eps_met, var_rho_met, var_log_nu_met, verbose, c_beta, c_eps, c_nu, c_rho)
}

